sudo: false
matrix:
  fast_finish: true
  include:
    - python: "3.5.3"
      env: TOXENV=lint
    - python: "3.5.3"
      env: TOXENV=pylint
    - python: "3.5.3"
      env: TOXENV=typing
    - python: "3.5.3"
      env: TOXENV=cov
      after_success: coveralls

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox coveralls
language: python
script: travis_wait 30 tox --develop
services:
  - docker
deploy:
  skip_cleanup: true
  provider: script
  script: script/travis_deploy
  on:
    branch: dev
    condition: $TOXENV = lint
